version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - UVICORN_RELOAD=true
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "false"
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]